### ISSUE TITLE
Sign in with Github button missing/ cannot access sso

### ISSUE THREAD

**Issue by nbob31** [reportportal/service-authorization#180]
I have configured my Report Portal version 5.1.0 to use Github. When I go to the login page the github button is missing and I can only get to the login by directly going to  to the url `reportportalurl.com/uat/sso/login/github`directly after I login it brings me to the login page with the error `Could not obtain access token`. 

ENV:
Report Portal 5.1.0
AWS/Kubernetes

**Comment by rvichery** [comment]
@nbob31 I am getting a similar error, how did you fix your issue ?

**Comment by nbob31** [comment]
I was not able to resolve it I reopened the issue in the main reportportal repo here - https://github.com/reportportal/reportportal/issues/936
