### ISSUE TITLE
Email not synchronised after change

### ISSUE THREAD

**Issue by alexandrsemak** [reportportal/service-authorization#243]
Reportportal:

Version 5.7.0

We deploy RP in kubernetes with LDAP configuration, after upgrade domain in organisation LDAP email not synced in user configuration

**Comment by alena-babrova** [comment]
Hello @alexandrsemak,
Indeed, email sync doesn't work for existing LDAP users. 
The bug is registered in our backlog and we will discuss with our team how to make it better.

Thank you for your contribution!

**Comment by alena-babrova** [comment]
Dear @alexandrsemak 
The bug has been fixed. It will be available in the 5.7.5 version.
