### ISSUE TITLE
LDAPS protocol support

### ISSUE THREAD

**Issue by nberezin** [reportportal/service-authorization#26]
https://github.com/reportportal/service-authorization/blob/1280d8efd60ebf0c977bd5fbf42015b1b260355e/src/main/java/com/epam/reportportal/auth/store/entity/ldap/AbstractLdapConfig.java#L37

Is there any chance to have ldaps protocol support added?

**Comment by avarabyeu** [comment]
@nberezin feel free to commit it. Not sure we can test it out due to environment absence, but i see no problems to adjust regexp pattern

**Comment by DzmitryHumianiuk** [comment]
@nberezin up

**Comment by avarabyeu** [comment]
@nberezin Unfortunately, we have no environment to check it, but validation will be adjusted in version 4.0.0

**Comment by nberezin** [comment]
Sorry for not replying, look like I missed the updates for git. I'm not a Java developer, so it is hard for me to get a dev environment for trying to check if the ldaps will actually work even if the fix is just in regex.
