### ISSUE TITLE
Service wants to connect to registry hostname

### ISSUE THREAD

**Issue by triesz** [reportportal/service-authorization#31]
Hi @avarabyeu ,

I am trying to terraform reportportal and start it on AWS.

I have set these environment variables for the container

```
    ev1name = "RP_PROFILES"
    ev1val = "docker"
    ev2name = "RP_SESSION_LIVE"
    ev2val = "86400"
    ev3name = "RP_MONGO_HOST"
    ev3val = "${module.reportportal-dns-int-a.dns-entry}"
    ev4name = "RP_MONGO_PORT"
    ev4val = "27017"
    ev5name = "RP_MONGO_DB_NAME"
    ev5val = "reportportal"
```

but still getting this exception and the service-authorization task eventually dies.

![image](https://user-images.githubusercontent.com/5139343/36389422-4e341290-159f-11e8-843a-5534e98622b3.png)

Is there a way to configure this?

Thanks a lot

**Comment by triesz** [comment]
workaround was adding "registry" hostname with extraHosts to the task definition:
```
      "extraHosts": [
        {
          "hostname": "registry",
          "ipAddress": "${extraHostIp}"
        }
      ],
```

**Comment by avarabyeu** [comment]
@triesz thanks!
Can we close it?

**Comment by triesz** [comment]
Hi @avarabyeu ,

sorry, let me put a bit more meat around this, although now this does not look to be the best place for tracking this problem... I recently had to deploy reportportal on AWS and it was extremely difficult due to a list of issues, and this was only the very first one of those...

The core problem is the combination of these 2 things:
1) AWS ECS does not allow user defined network https://github.com/aws/amazon-ecs-agent/issues/437
2) Reportportal components assume that they can reach each other by hostname

When you use docker-compose to start reportportal it creates a user defined network and one of its services is a DNS which automatically makes all service names resolveable for each other.

AWS ECS service however starts containers using the default docker bridge which does not have such DNS service. Therefore the containers used by reportportal cannot reach each other based on the names.

So to support more portable reportportal deployment and scaling in various environments the followings would be very-very helpful to make configurable:
- hostname (or IP) of the consul host should be configurable for all services (currently "registry" hostname is wired in some places)
- port of consul should be configurable for all services
- IP / hostname preference should be configurable for all services (for the consul registration)
- service offering port should be configurable for all services (currently multiple service containers listen on the same 8080 port and this does not seem to be configurable)

I have finally managed to use ECS on one t2.medium machine to run reportportal but just to give you an idea all these "hacks" were necessary due to the lack of the above configuration possibilities:
- I had to open up 8500 consul port, to listen on the hosting EC2 machine external IP too
- for those services where it is configure I had set env var CONSUL_ADDR=<IP of hosting EC2 machine>
- for the rest of the containers I had to use extraHost ("registry" = <IP of hosting EC2 machine>)
- had to set the hostnames for all containers, based on your docker-compose.yml service names
- had to provision this on the hosting EC2 machine (user_data):
```
docker network create rp_net
echo -e "* * * * * for i in \`/usr/bin/docker ps | /bin/grep -v CONTAINER | /bin/grep -v ecs-agent | /bin/awk '{print \$1}' \`; do /usr/bin/docker network connect rp_net \$i; done > /tmp/cronout 2>&1" | crontab -
```

With the above listed configuration possibilities most of this would have been unnecessary, reportportal deployment would be easily portable across service providers and easier to scale.

**Comment by triesz** [comment]
An easy way to reproduce some of this probs - without some AWS-specific ones -, is to try to start reportportal on a docker swarm:

`docker stack deploy reportportal --compose-file docker-compose.yml`

**Comment by vishallanke** [comment]
Since last few days, I am trying to solve a problem. I posted it on various forums , however, I did not receive any answer. So, I  thought to post it here.
I want to -
1 - Install complete ReportPortal on ECS (AWS Container) [We do not want to use EC2 Instance for deployment]
2 - Postgres DB should not be in same container. Host it separately, might be in container or AWS DB [ Again no EC2 Instance]
3 - Then, I want to Integrate ReportPortal and Postgres
Inside DockerHub, there are docker images for various services like authorization, UI etc. I pull one of the image(service-ui) and deploy it inside AWS container. ReportPortal UI gets opened. However, it seems  need to deploy other services like Authorization, Analyser etc.  However, I did  not find any document which will help me setting up complete ReportPortal in ECS.
Is it possible to deploy ReportPortal  in ECS and if yes, then can anyone share any link ?

**Comment by Mahesh81** [comment]
> Since last few days, I am trying to solve a problem. I posted it on various forums , however, I did not receive any answer. So, I thought to post it here.
> I want to -
> 1 - Install complete ReportPortal on ECS (AWS Container) [We do not want to use EC2 Instance for deployment]
> 2 - Postgres DB should not be in same container. Host it separately, might be in container or AWS DB [ Again no EC2 Instance]
> 3 - Then, I want to Integrate ReportPortal and Postgres
> Inside DockerHub, there are docker images for various services like authorization, UI etc. I pull one of the image(service-ui) and deploy it inside AWS container. ReportPortal UI gets opened. However, it seems need to deploy other services like Authorization, Analyser etc. However, I did not find any document which will help me setting up complete ReportPortal in ECS.
> Is it possible to deploy ReportPortal in ECS and if yes, then can anyone share any link ?

Hi @vishallanke 
Im getting into the same concept of hosting reportportal in ECS, can you provide your painpoints and how to overcome. can we achieve it in ECS ?

**Comment by vishallanke** [comment]
@Mahesh81 
https://github.com/reportportal/service-api/issues/1202

Report Portal do not support AWS ECS.

**Comment by Mahesh81** [comment]
> @Mahesh81
> [reportportal/service-api#1202](https://github.com/reportportal/service-api/issues/1202)
> 
> Report Portal do not support AWS ECS.

Thanks Vishal (@vishallanke). So EKS is best option for AWS ?

**Comment by vishallanke** [comment]
Yes EKS is the best options.
